In [2]:
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pylab as plt
import sympy
import forecastio
import requests
import time
from selenium import webdriver
import re

In [30]:

driver = webdriver.Chrome()
driver.get('https://www.premierleague.com/tables')

main_content = driver.find_element_by_css_selector('#mainContent')
Contents = main_content.find_elements_by_css_selector('.tableBodyContainer tr:not(.expandable)')

df = pd.DataFrame(columns = ['Position', 'Club', 'Played', 'Won', 'Drawn', 'Lost', 'GF', 'GA', 'GD', 'Points'])

for i in range(0, 0+20):
    Position = Contents[i].find_elements_by_css_selector('#Tooltip')[0].text
    Club = Contents[i].find_elements_by_css_selector('a')[0].text
    Played = Contents[i].find_elements_by_css_selector('td')[3].text
    Won = Contents[i].find_elements_by_css_selector('td')[4].text
    Drawn = Contents[i].find_elements_by_css_selector('td')[5].text
    Lost = Contents[i].find_elements_by_css_selector('td')[6].text
    GF = Contents[i].find_elements_by_css_selector('td')[7].text
    GA = Contents[i].find_elements_by_css_selector('td')[8].text
    GD = Contents[i].find_elements_by_css_selector('td')[9].text
    Points = Contents[i].find_elements_by_css_selector('td')[10].text
    
    data = {'Position': Position,
            'Club': Club,
            'Played': Played,
            'Won': Won,
            'Drawn': Drawn,
            'Lost': Lost,
            'GF': GF,
            'GA': GA,
            'GD': GD,
            'Points': Points, }
    
    df.loc[len(df)] = data
    
    driver.close

df

,Position,Club,Played,Won,Drawn,Lost,GF,GA,GD,Points
0,1,Manchester City,27,23,3,1,79,20,+59,72
1,2,Manchester United,27,17,5,5,51,19,+32,56
2,3,Liverpool,27,15,9,3,61,31,+30,54
3,4,Chelsea,27,16,5,6,49,23,+26,53
4,5,Tottenham Hotspur,27,15,7,5,52,24,+28,52
5,6,Arsenal,27,13,6,8,51,36,+15,45
6,7,Burnley,27,9,9,9,21,24,-3,36
7,8,Leicester City,27,9,8,10,39,40,-1,35
8,9,Everton,27,9,7,11,32,46,-14,34
9,10,Bournemouth,27,8,7,12,31,41,-10,31
10,11,Watford,27,8,6,13,37,47,-10,30
11,12,West Ham United,27,7,9,11,34,46,-12,30
12,13,Newcastle United,27,7,7,13,25,36,-11,28
13,14,Brighton and Hove Albion,27,6,10,11,22,36,-14,28
14,15,Crystal Palace,27,6,9,12,25,42,-17,27
15,16,Swansea City,27,7,6,14,20,37,-17,27
16,17,Huddersfield Town,27,7,6,14,23,47,-24,27
17,18,Southampton,27,5,11,11,28,40,-12,26
18,19,Stoke City,27,6,7,14,27,53,-26,25
19,20,West Bromwich Albion,27,3,11,13,21,40,-19,20